version: "3"
services:
  web:
    image: lefuturiste/scoutsenroute
    environment:
      STAILEU_PUBLIC: d0567390-62ab-4fa3-82b4-b7b522a66b41
      STAILEU_PRIVATE: e59f9306-69f7-48bc-86ec-cb9e7df0aa2d
      STAILEU_URL: http://local.dev:2654/login/execute
      INSTAGRAM_ID: 47bcbde15c29448ba2d81ffe3777a2fe
      INSTAGRAM_SECRET: fdfecf228fbc4d9390a6ef3d98b88203
      INSTAGRAM_REDIRECT_URI: http://localhost:8000/instagram/authorize
      INSTAGRAM_ACCESS_TOKEN: 6486667301.47bcbde.b76ebaa713f842b3be38a0c5659f5636
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: scoutsenroute
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "8976:80"
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8020:8000"
  db:
    image: mysql:5.7
    ports:
    - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scoutsenroute
